services:
  # PHP service with Symfony
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /app
    user: appuser
    command: >
      sh -c "sudo chown -R appuser:appuser /app && chmod +x /app/setup.sh && /app/setup.sh && php-fpm"
    volumes:
      - ./:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: mysql://symfony:symfony@database:3306/symfony?serverVersion=8.0

  # Web server (Nginx)
  nginx:
    image: nginx:alpine
    ports:
      - "18080:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # MySQL database
  database:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql

  # Node service for React development
  node:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "echo 'Node.js container for React development is ready'"

volumes:
  db-data:
